name: 'crypto_analytics_dbt'
version: '1.0.0'
config-version: 2

# This MUST match the profile name in profiles.yml
profile: 'crypto_analytics_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  crypto_analytics_dbt:
    +materialized: table
    # default schema for all your models = PARROT_FEAT
    +schema: PARROT_FEAT

snapshots:
  crypto_analytics_dbt:
    # snapshots go into PARROT_SNAP schema
    +schema: PARROT_SNAP
